version: 0.2 

#env: 
  #variables: 
     # key: "value" 
     # key: "value" 
  #parameter-store: 
     # key: "value" 
     # key: "value" 
phases: 
  install:
    runtime-versions:
        docker: 19 
  pre_build: 
    commands: 
    - REPOSITORY_URI=773710653318.dkr.ecr.us-east-1.amazonaws.com/cicd
    - IMAGE_TAG=2
    - AWS_REGION=us-east-1
    # update the following line with your own region
    - aws --version
    - aws sts get-caller-identity
    - ls -l
    - echo Logging in to Amazon ECR.... 
    - $(aws ecr get-login --no-include-email --region $AWS_REGION) 
    - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.8/2020-09-18/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/bin
    - aws eks --region $AWS_REGION update-kubeconfig --name eks-mark
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t $REPOSITORY_URI:latest . 
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
    - echo Build completed on `date` 
  post_build: 
    commands: 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker images
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file...
    - printf '[{"name":"cicd","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - kubectl apply -f tomcat-app.yml
    - kubectl set image deployment/tomcat-deployment tomcatcon=$REPOSITORY_URI:$IMAGE_TAG
    - echo Completion on `date`
artifacts:
  files:
    - '**/*'
#artifacts: 
    # - location 
    # - location 
  #discard-paths: yes 
  #base-directory: location 
#cache: 
  #paths: 
    # - paths 
 

