version: 0.2 

#env: 
  #variables: 
     # key: "value" 
     # key: "value" 
  #parameter-store: 
     # key: "value" 
     # key: "value" 
phases: 
  install:
    runtime-versions:
        docker: 19 
  pre_build: 
    commands: 
     # update the following line with your own region
    - aws --version
    - aws sts get-caller-identity
    - ls -l
    - yum install -y jq
    - ECR_URL=$(cat $BuildProperty | jq -r '.ECR_URL')
    - ECR_REPO=$(cat $BuildProperty | jq -r '.ECR_REPO')
    - echo Logging in to Amazon ECR.... 
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t $ECR_URL/$ECR_REPO:codebuild_$CODEBUILD_BUILD_NUMBER . 
    - echo Build completed on `date` 
  post_build: 
    commands: 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker images
    - docker push $ECR_URL/$ECR_REPO:codebuild_$CODEBUILD_BUILD_NUMBER
    - echo Post Completion on `date`
artifacts:
  files:
    - '**/*'
#artifacts: 
    # - location 
    # - location 
  #discard-paths: yes 
  #base-directory: location 
#cache: 
  #paths: 
    # - paths 
 

